# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\MyProjects\Cypress\RTC_P4_WDT_Example01\RTC_P4_WDT_Example01.cydsn\RTC_P4_WDT_Example01.cyprj
# Date: Mon, 10 Aug 2020 08:22:09 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\MyProjects\Cypress\RTC_P4_WDT_Example01\RTC_P4_WDT_Example01.cydsn\TopDesign\TopDesign.cysch
# Project: D:\MyProjects\Cypress\RTC_P4_WDT_Example01\RTC_P4_WDT_Example01.cydsn\RTC_P4_WDT_Example01.cyprj
# Date: Mon, 10 Aug 2020 08:22:07 GMT
